export const project = [
  {
    id: 1,
    serialNo: "01",
    name: "Streamify",
    image: "/assets/Streamify.png",
    tag1: "React",
    tag2: "Express",
    tag3: "MongoDB",
    link: '/project/Streamify',
  },
  {
    id: 2,
    serialNo: "02",
    name: "PeaceHub",
    image: "/assets/PeaceHub.jpeg",
    tag1: "React",
    tag2: "Figma",
    tag3: "TailwindCSS",
    link: '/project/PeaceHub',
  },
  {
    id: 3,
    serialNo: "03",
    name: "Brainwave",
    image: "/assets/Brainwave.jpeg",
    tag1: "React",
    tag2: "javaScript",
    tag3: "TailwindCSS",
    link: '/project/Brainwave',
  },
];

export const projectsFull = [
  {
    id: 1,
    serialNo: "01",
    name: "Streamify",
    image: "/assets/Streamify.png",
    tag1: "React",
    tag2: "Express",
    tag3: "MongoDB",
    link: '/project/Streamify',
  },
  {
    id: 2,
    serialNo: "02",
    name: "PeaceHub",
    image: "/assets/PeaceHub.jpeg",
    tag1: "React",
    tag2: "Figma",
    tag3: "TailwindCSS",
    link: '/project/PeaceHub',
  },
  {
    id: 3,
    serialNo: "03",
    name: "Brainwave",
    image: "/assets/Brainwave.jpeg",
    tag1: "React",
    tag2: "javaScript",
    tag3: "TailwindCSS",
    link: '/project/Brainwave',
  },
  {
    id: 4,
    serialNo: "04",
    name: "SafenGo",
    image: "/assets/Safe-n-go.jpeg",
    tag1: "React",
    tag2: "ExpressJs",
    tag3: "MongoDB",
    link: '/project/SafenGo',
  },
  {
    id: 5,
    serialNo: "05",
    name: "Movie Base",
    image: "/assets/MovieBase.jpeg",
    tag1: "React",
    tag2: "Appwrite",
    tag3: "TailwindCSS",
    link: '/project/MovieBase',
  },
];
